# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: ja-JP

reviews:
  request_changes_workflow: true
  poem: false
  collapse_walkthrough: false

  # レビュー強化機能
  auto_apply_labels: true

  path_filters:
    - "webapp/**"
    - "admin/**"
    - "shared/**"
    - "prisma/**"
    - "supabase/**"
    - "docs/**"
    - "!**/*.md"
    - "!**/*.mdx"
    - "!**/*.svg"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.lock"
    - "!**/pnpm-lock.yaml"
    - "!**/yarn.lock"
    - "!**/package-lock.json"
    - "!**/dist/**"
    - "!**/.next/**"
    - "!**/coverage/**"
    - "!**/*.snap"
  auto_review:
    drafts: true
  labeling_instructions: []

  pre_merge_checks:
    docstrings:
      mode: "off"
