# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: ja-JP

# ナレッジベース: プロジェクト固有のアーキテクチャガイドとルール
knowledge_base:
  code_guidelines:
    filePatterns:
      - "docs/admin-architecture-guide.md"
      - "docs/admin-ui-guidelines.md"
      - "docs/design-document-rules.md"
      - "CLAUDE.md"

reviews:
  request_changes_workflow: true
  poem: false
  collapse_walkthrough: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"

  # レビュースタイル
  profile: assertive

  # レビュー強化機能
  auto_apply_labels: true

  path_filters:
    - "webapp/**"
    - "admin/**"
    - "shared/**"
    - "prisma/**"
    - "supabase/**"
    - "docs/**"
    - "!**/*.md"
    - "!**/*.mdx"
    - "!**/*.svg"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.lock"
    - "!**/pnpm-lock.yaml"
    - "!**/yarn.lock"
    - "!**/package-lock.json"
    - "!**/dist/**"
    - "!**/.next/**"
    - "!**/coverage/**"
    - "!**/*.snap"

  # パス別のレビュー指示
  path_instructions:
    - path: "admin/src/server/contexts/**"
      instructions: "docs/admin-architecture-guide.md に従ってレビューしてください。"

    - path: "admin/src/client/**"
      instructions: "docs/admin-ui-guidelines.md に従ってレビューしてください。"

    - path: "webapp/src/**"
      instructions: "CLAUDE.md の「Next アプリケーション」セクションに従ってレビューしてください。"

    - path: "admin/src/server/contexts/report/**"
      instructions: "docs/report-format.md と docs/scope-by-2026Jan.md に従ってレビューしてください。"

  auto_review:
    drafts: true
  labeling_instructions: []

  pre_merge_checks:
    docstrings:
      mode: "off"
