# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: ja-JP

reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "webapp/**"
    - "admin/**"
    - "shared/**"
    - "prisma/**"
    - "supabase/**"
    - "docs/**"
    - "!**/*.md"
    - "!**/*.mdx"
    - "!**/*.svg"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.lock"
    - "!**/pnpm-lock.yaml"
    - "!**/yarn.lock"
    - "!**/package-lock.json"
    - "!**/dist/**"
    - "!**/.next/**"
    - "!**/coverage/**"
    - "!**/*.snap"
  auto_review:
    enabled: true
    drafts: true
  labeling_instructions: []
