import { test, expect } from "@playwright/test";

test("年度帳簿の作成・帳簿情報の編集", async ({ page }) => {
  const name = `e2e-books-${Date.now()}`;
  await page.goto("/politicians/new");
  await page.getByLabel("氏名").fill(name);
  await page.getByLabel("スラッグ").fill(name);
  await page.getByLabel("当選日").fill("2026-02-08");
  await page.getByRole("button", { name: "作成", exact: true }).click();
  await expect(page).toHaveURL("/politicians");
  const politicianCard = page.locator('[data-slot="card"]').filter({ has: page.getByRole("heading", { name, exact: true }) });
  await politicianCard.getByRole("link", { name: "年度帳簿" }).click();
  await expect(page.getByRole("heading", { name: `${name}の帳簿一覧` })).toBeVisible();
  await page.getByLabel(/^年度/).fill("2026");
  await page.getByRole("button", { name: "帳簿を作成" }).click();
  const card = page.locator('[data-slot="card"]').filter({ has: page.getByRole("heading", { name: "2026年度" }) });
  await expect(card).toContainText("未公開");
  await expect(card).toContainText("0件の下書き");
  await expect(card.getByRole("link", { name: "スキャンする" })).toHaveAttribute("href", /\/books\/\d+\/scan$/);
  await expect(card.getByRole("link", { name: "仕訳を確認" })).toHaveAttribute("href", /\/books\/\d+\/entries$/);
  await card.locator("summary").click();
  await card.getByLabel("時点の日付").fill("2026-08-20");
  await card.getByLabel("次回更新の案内").fill("次回は11月ごろ");
  await card.getByLabel("活用方針").fill("調査研究に活用します");
  await card.getByRole("button", { name: "帳簿情報を保存" }).click();
  await expect(page.getByText("帳簿情報を保存しました", { exact: true })).toBeVisible();
  await page.reload();
  await card.locator("summary").click();
  await expect(card.getByLabel("時点の日付")).toHaveValue("2026-08-20");
  await expect(card.getByLabel("次回更新の案内")).toHaveValue("次回は11月ごろ");
  await expect(card.getByLabel("活用方針")).toHaveValue("調査研究に活用します");
  await page.getByRole("link", { name: "議員一覧へ" }).click();
  await politicianCard.getByRole("button", { name: "削除", exact: true }).click();
  await page.getByRole("button", { name: "削除する", exact: true }).click();
  await expect(politicianCard).toHaveCount(0);
});
